name: 'Automatic Version Bumper'
description: 'Automatically bumps version and creates releases based on PR title conventions'
author: 'Technopalette'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for creating releases and pushing tags'
    required: true
  initial_version:
    description: 'Initial version from secrets (format: x.y.z)'
    required: true
  force_initial:
    description: 'Force use of initial version (ignore existing tags)'
    required: false
    default: 'false'

outputs:
  new_version:
    description: 'The new version number that was created'

runs:
  using: 'node20'
  main: 'index.js'
  env:
    CORE_ACCESS_TOKEN: ${{ secrets.CORE_ACCESS_TOKEN }}